apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: letsencrypt
  name: letsencrypt
  namespace: moreorless-site
spec:
  replicas: 1
  selector:
    app: letsencrypt
    deploymentconfig: letsencrypt
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: letsencrypt
        deploymentconfig: letsencrypt
    spec:
      containers:
      - env:
        - name: OPENSHIFT_MASTER_INTERNAL
          value: 10.132.0.2
        image: moreorless-site/letsencrypt:latest
        imagePullPolicy: Always
        name: letsencrypt
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: letsencrypt-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - letsencrypt
      from:
        kind: ImageStreamTag
        name: letsencrypt:latest
        namespace: moreorless-site
    type: ImageChange
